### ISSUE TITLE
API repository answers with 401 for APIs which do not sit in the repository -- the answer should be 404

### ISSUE THREAD

**Issue by ahmetaker** [hltfbk/Excitement-Open-Platform#503]
Hi,
I came accross the excitement project and think it is a great solution for text entailment. Without any problems I was able to use it so thanks for this.

However, when I tried to integrate it with some implementations of mine that use other APIs (some local ones) I started experiencing problems. I use Maven to build my application. Maven checks for the APIs all the repositories including the one where the excitment project APIs sit. The problem is that when Maven checks your repository for my local APIs I get a message 401 instead of 404. It seems that your repository does not return "not found" when an API is not found. I would appreciate if you could look at this problem.

I hope I explained my problem. If not please let me know. Also the exact problem is described here (on different case):

http://forums.jfrog.org/401-when-using-Gradle-and-anonymous-access-td7578040.html

Thanks,
Ahmet

**Comment by rzanoli** [comment]
When a user tries to access a resource for which he is not authorized, Artifactory default behavior is to indicate that the resource exists, but is protected.For example, an anonymous request will result in a request for authentication (401), and a request by an unauthorized authenticated users will simply be denied. 

We configured Artifactory to return a 404 - Not Found response in these cases by setting Hide Existence of Unauthorized. With these changes the issue seems to be solved; in case of other warnings regarding it we will need to investogate further.
